### ISSUE TITLE
design: 依存関係があるリソースでのCore〜Handlersのやりとり

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/autoscaler#14]
現在は各Handlersに対しリソースグループに所属する全てのリソースのあるべき状態(Desired)を渡している。
この方法の場合、ELB+サーバの組み合わせでのサーバのスケールアップ/ダウンのようなケースをどう扱うか?

- 期待する処理は以下の通り
  - ELBから切り離し
  - サーバのスケールアップ/ダウン
  - ELBへの接続
- Handler側で渡されたDesiredを解釈する形だと組み合わせの分だけHandlerが必要になる
  (GSLB+サーバやLB+サーバといった組み合わせもあり得る)

**Comment by yamamoto-febc** [comment]
対応案: フックの導入 & 処理対象リソースごとの処理への切り替え

### Handlers側の変更

- Coreで利用するHandlerを指定する形ではなく、一定のHandlersを起動しておきChain of Responsibilityで処理
- 実装すべきgRPCのfuncとしてPreHandle/PostHandleを追加

### Core側の変更

- 現在のCompute処理はそのまま
- 処理対象のリソースグループ内のリソースの末端から順次Handlerを呼び出し(幅優先の逆順で処理)
- Handler呼び出し前後にそれぞれPreHandle/PostHandleを呼び出し

### 具体例

以下のリソースグループに対する垂直スケールを行うケース

```yaml
# GSLB配下に置いたサーバを順次スケールアップする例
front:
    - type: GSLB 
      selector:
        names: ["example"]
      resources:
        - type: Server
          selector: 
            names: ["example"]
            zones: ["is1b", "tk1b]
```

- 1: Computeで各リソースの情報を算出
- 2: リソースグラフの末端(このケースではサーバ)から順次Handlersの呼び出し

```yaml
# Handlerに渡すパラメータのイメージ
target:
  - type: Server
     id: xxxx
     cpu: 2
     memory: 4
     # ...
     parent:
       - type: GSLB
          ID: xxxx
          # ...
```

- 3: Handlers側は自身が関心を持つリソースが渡されたか判定、必要に応じて処理

```
# Handlers側の処理イメージ
- GSLB(サーバのattach/detachハンドラ)
  - PreHandle: parentがGSLBなサーバが渡されたらサーバをGSLBから切断
  - Handle: 何もしない
  - PostHandle: parentがGSLBなサーバが渡されたらサーバをGSLBへ接続

- Server(垂直スケールハンドラ)
  - PreHandle: 何もしない
  - Handle: サーバのプラン変更
  - PostHandle: 何もしない 
```

検討点: 現在は各ハンドラーの呼び出しごとにリソースグループのComputeを行っていたが不要かもしれない
