### ISSUE TITLE
Computedから親Computedへの参照

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/autoscaler#18]
CoreからHandlersへパラメータを渡す際、以下のようなネストしたリソースの場合は子リソースに対し親リソースへの参照を持たせている。

```yaml
    - type: DNS
      selector:
        names: ["example"]
      resources:
        - type: Server
          selector:
            names: ["child"]
            zone: ["is1a"]
          zone: "is1a"
```

リソースから算出される`Computed`についても同じように親リソースに対する`Computed`の情報を持たせたいがいくつか問題がある。

- いつ算出するか?
- 親がSelectorに対し複数存在するケースが考えられるがどうするか?
