### ISSUE TITLE
親子関係のあるリソースでの名前付きプラン

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/autoscaler#190]
以下のようなリソース定義だった場合、DesiredStateNameを指定して名前付きプランを利用しようとするとELB側に対応する名前付きプランが存在しないためエラーとなる。

```yaml
    resources:
      - type: ELB
        resources:
          - type: ServerGroup
            plans:
              - {name: "smallest", size: 0}
              - {name: "medium", size: 3}
              - {name: "largest", size: 5}
```

親リソースでも名前付きプランを定義するようにすれば解決するが煩雑。  
このため、以下のように実装した方が良さそう。

- DesiredStateNameが指定された場合、リソースグループ内の前リソース種別に該当するプランがあるか確認
- 存在するプランはそのまま
- 存在しない場合はDesiredStateNameが指定されていないものとして振る舞う
