### ISSUE TITLE
水平スケールでのdown時にサーバが追加されるケースがある

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/autoscaler#196]
以下のようなコンフィギュレーションで`autoscaler inputs direct down`するとサーバが作成されるケースがある。

```yaml
        - type: ServerGroup

          name: "server-group"
          zone: "is1a"

          min_size: 0   # 最小インスタンス数
          max_size: 5   # 最大インスタンス数
```

作成された際、さくらのクラウド上には`server-group-*`という名前のサーバは存在しなかった。
本来は無視されるのが正しい。
