### ISSUE TITLE
対象リソースの選択方法

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/autoscaler#198]
以下のように親子関係があるリソースが定義されていた場合、ELBだけスケールアップしたい場合やサーバグループだけスケールアウトしたい場合、現在は`actions`を定義し実行するハンドラを限定することで対応できるが、不要な計算処理まで動いてしまう。

例: ELBのスケールアップにもかかわらずサーバグループのインスタンス追加処理(計算だけ)が実行される

```yaml
    resources:
      - type: ELB
        selector:
          names: ["example"]
        resources:
        - type: ServerGroup
          name: "server-group" 
          zone: "is1a"
```

また、`actions`でハンドラーの組を指定するというのが直感的に分かりづらいかもしれない。

コンフィグのレイアウト変更などの設計変更も視野に入れて再考する。
