### ISSUE TITLE
サーバグループ: 台数が0台の場合のupが無視される

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/autoscaler#216]
以下のようなケースで`server-group`というプレフィックスを持つサーバが1台もない時にUpリクエストを送ると無視される

```yaml
resources:
  - type: LoadBalancer
    name: "lb"
    selector:
      names: ["example"]
      zones: ["is1a"]
    resources:
      - type: ServerGroup
        name: "server-group"
        zone: "is1a"

        min_size: 1   # 最小インスタンス数
        max_size: 3  # 最大インスタンス数
```

詳細:
```
$ autoscaler version -a
v0.1.0 darwin/amd64, build c843011
```
