### ISSUE TITLE
子リソースがある場合のresource-nameパラメータのバリデーション誤り

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/autoscaler#228]
related: #215 

以下のように子リソースがある場合、リソースが2つ以上となるためresource-nameパラメータを必須にしたいが、現在はOKと判定され`elb`が操作対象となってしまう。

```yaml
  - type: ELB
    name: "elb"
    selector:
      names: ["example"]
    resources:
    - type: ServerGroup
      name: "server-group"
      zone: "is1a"
```
