### ISSUE TITLE
リソースの親子関係の定義方法を変更

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/autoscaler#282]
from:
- https://github.com/sacloud/autoscaler/pull/201#issue-938393101
- https://github.com/sacloud/autoscaler/issues/198#issuecomment-874723040

#198 や #201 で検討したwrapperの導入を再検討する。

## 概要

resourcesに指定するリソースは各自に`resources`というフィールドがあり、定義をネストさせることで親子関係を示せるようになっている。
```yaml
    resources:
      - type: ELB
        name: "elb" 
        selector:
          names: ["example"]
        resources:
        - type: ServerGroup
          name: "server-group" 
          zone: "is1a"
```

この例の場合、サーバの水平スケールだけ行いたい場合でもELBの定義&nameの設定が必要となっており若干煩雑である。
また、resourcesのネストは実質2段階まで(親-子まで)となっており、多段ネストさせる意味合いは薄い。

このため、よりコンフィギュレーションをよりシンプルにするために、wrapperを導入した上でresourcesのネストを除去したい。

### TO-BE

```yaml
    resources:
      - type: ServerGroup
        name: "server-group" 
        zone: "is1a"
        
        # 親リソースの定義
        wrapper:
         # nameは不要にできるかも
          type: ELB
          selector:
            names: ["example"]
```

この方法で各リソースでのname指定が不要になれば、Up/Down時のResourceName指定も省略できるなど派生的なメリットもある。
