### ISSUE TITLE
アクションの定義

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/autoscaler#53]
アクションとハンドラーの組み合わせを定義可能にし、リクエスト時のパラメータに応じて利用可能にする。

例: 以下のようにリソースを定義した場合、デフォルトだとUp/Downリクエストで

- ELBの垂直スケール
- サーバの垂直スケール
  - ELBからのデタッチ/アタッチ

が全て動く。

```yaml
      - type: ELB
        selector:
          names: ["example"]
        plans:
          - cps: 100
          - cps: 500
          - cps: 1000
        resources:
          - type: Server
            selector:
              names: ["example-01"]
              zone: "is1a"
          - type: Server
            selector:
              names: ["example-02"]
              zone: "is1a"
```

この例でELBのスケールアップだけのように個別のハンドラだけ実行したいユースケースが考えられる。  
これを実現するために、Configurationでアクション名とハンドラーのリストの組み合わせを定義可能にしておき、リクエスト時にアクション名を指定可能にしておく。

リクエスト時のパラメータとしては定義済みなため、Core側のConfigurationの実装とアクション名からのハンドラーの選択部分を実装するようにする。

例:

```yaml
# グローバル、またはリソースグループごとにアクションを定義可能にする
actions:
  elb-vertical-scaling: # アクション名
    - elb-vertical-scaler # ハンドラーのリスト

  server-vertical-scaling: 
    - server-vertical-scaler
    - elb-servers-handler
```

リクエスト時にアクション名が未指定、またはデフォルト値の場合は先頭のアクション(YAMLでの定義順とは限らない)を暗黙的に利用するようにし、もしアクションが1件も定義されていなければ全てのハンドラを実行するようにする。
